"""
This type stub file was generated by pyright.
"""

def prepare_shape_strides_dtype(shape, strides, dtype, order): # -> tuple[tuple[int] | Any, tuple[int] | Any | tuple[()] | tuple[int, ...], dtype[Any]]:
    ...

