"""
This type stub file was generated by pyright.
"""

class GridGroup:
    """A cooperative group representing the entire grid"""
    def sync() -> None:
        """Synchronize this grid group"""
        ...
    


def this_grid() -> GridGroup:
    """Get the current grid group."""
    ...

