"""
This type stub file was generated by pyright.
"""

from numba.core.descriptors import TargetDescriptor
from numba.core.options import TargetOptions

class CUDATargetOptions(TargetOptions):
    ...


class CUDATarget(TargetDescriptor):
    def __init__(self, name) -> None:
        ...
    
    @property
    def typing_context(self): # -> CUDATypingContext:
        ...
    
    @property
    def target_context(self): # -> CUDATargetContext:
        ...
    


cuda_target = ...
