"""
This type stub file was generated by pyright.
"""

from numba.core.extending import models
from numba.core import types
from numba.cuda.types import Dim3, GridGroup

cuda_data_manager = ...
register_model = ...
@register_model(Dim3)
class Dim3Model(models.StructModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


@register_model(GridGroup)
class GridGroupModel(models.PrimitiveModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


@register_model(types.Float)
class FloatModel(models.PrimitiveModel):
    def __init__(self, dmm, fe_type) -> None:
        ...
    


