"""
This type stub file was generated by pyright.
"""

'''
The runtime API is unsupported in the simulator, but some stubs are
provided to allow tests to import correctly.
'''
class FakeRuntime:
    def get_version(self): # -> tuple[Literal[-1], Literal[-1]]:
        ...
    
    def is_supported_version(self): # -> Literal[True]:
        ...
    
    @property
    def supported_versions(self): # -> tuple[tuple[Literal[-1], Literal[-1]]]:
        ...
    


runtime = ...
