"""
This type stub file was generated by pyright.
"""

import warnings
import setuptools
from numba.core.errors import NumbaPendingDeprecationWarning
from .cc import CC
from .decorators import export, exportmany

__pycc_deprecation_doc_url = ...
__pycc_pending_deprecation_message = ...
_pend_dep = ...
