"""
This type stub file was generated by pyright.
"""

from .registry import Rewrite, register_rewrite, rewrite_registry
from numba.core.rewrites import ir_print, static_binop, static_getitem, static_raise

"""
A subpackage hosting Numba IR rewrite passes.
"""
