"""
This type stub file was generated by pyright.
"""

def register(dmm, typecls): # -> Callable[..., Any]:
    """Used as decorator to simplify datamodel registration.
    Returns the object being decorated so that chaining is possible.
    """
    ...

default_manager = ...
register_default = ...
