"""
This type stub file was generated by pyright.
"""

from . import cloudpickle
from .cloudpickle import *

__doc__ = ...
__version__ = ...
__all__ = ["__version__", "Pickler", "CloudPickler", "dumps", "loads", "dump", "load", "register_pickle_by_value", "unregister_pickle_by_value"]
