"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod

"""
Target Descriptors
"""
class TargetDescriptor(metaclass=ABCMeta):
    def __init__(self, target_name) -> None:
        ...
    
    @property
    @abstractmethod
    def typing_context(self): # -> None:
        ...
    
    @property
    @abstractmethod
    def target_context(self): # -> None:
        ...
    


