"""
This type stub file was generated by pyright.
"""

"""
Useful options to debug LLVM passes

llvm.set_option("test", "-debug-pass=Details")
llvm.set_option("test", "-debug-pass=Executions")
llvm.set_option("test", "-debug-pass=Arguments")
llvm.set_option("test", "-debug-pass=Structure")
llvm.set_option("test", "-debug-only=loop-vectorize")
llvm.set_option("test", "-help-hidden")

"""
def create_pass_manager_builder(opt=..., loop_vectorize=..., slp_vectorize=...): # -> PassManagerBuilder:
    """
    Create an LLVM pass manager with the desired optimisation level and options.
    """
    ...

