"""
This type stub file was generated by pyright.
"""

from functools import cached_property

class YieldPoint:
    def __init__(self, block, inst) -> None:
        ...
    


class GeneratorInfo:
    def __init__(self) -> None:
        ...
    
    def get_yield_points(self): # -> dict_values[Any, Any]:
        """
        Return an iterable of YieldPoint instances.
        """
        ...
    


class VariableLifetime:
    """
    For lazily building information of variable lifetime
    """
    def __init__(self, blocks) -> None:
        ...
    
    @cached_property
    def cfg(self): # -> CFGraph:
        ...
    
    @cached_property
    def usedefs(self): # -> use_defs_result:
        ...
    
    @cached_property
    def livemap(self): # -> dict[Any, Any]:
        ...
    
    @cached_property
    def deadmaps(self): # -> dead_maps_result:
        ...
    


ir_extension_insert_dels = ...
class PostProcessor:
    """
    A post-processor for Numba IR.
    """
    def __init__(self, func_ir) -> None:
        ...
    
    def run(self, emit_dels: bool = ..., extend_lifetimes: bool = ...): # -> None:
        """
        Run the following passes over Numba IR:
        - canonicalize the CFG
        - emit explicit `del` instructions for variables
        - compute lifetime of variables
        - compute generator info (if function is a generator function)
        """
        ...
    
    def remove_dels(self): # -> None:
        """
        Strips the IR of Del nodes
        """
        ...
    


