"""
This type stub file was generated by pyright.
"""

"""Module for displaying information about Numba's gdb set up"""
_fields = ...
_gdb_info = ...
class _GDBTestWrapper:
    """Wraps the gdb binary and has methods for checking what the gdb binary
    has support for (Python and NumPy)."""
    def __init__(self) -> None:
        ...
    
    @property
    def gdb_binary(self):
        ...
    
    @classmethod
    def success(cls, status):
        ...
    
    def check_launch(self): # -> CompletedProcess[str]:
        """Checks that gdb will launch ok"""
        ...
    
    def check_python(self): # -> CompletedProcess[str]:
        ...
    
    def check_numpy(self): # -> CompletedProcess[str]:
        ...
    
    def check_numpy_version(self): # -> CompletedProcess[str]:
        ...
    


def collect_gdbinfo(): # -> _gdb_info:
    """Prints information to stdout about the gdb setup that Numba has found"""
    ...

def display_gdbinfo(sep_pos=...): # -> None:
    """Displays the information collected by collect_gdbinfo.
    """
    ...

if __name__ == '__main__':
    ...
