name: Ruff Check
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: src/cv2ext
          args: 'format --check'
      - uses: chartboost/ruff-action@v1
        with:
          src: src/cv2ext
          args: 'lint --check'
